# Generated by Django 5.0.1 on 2024-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_category_category_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='how_it_works',
            name='img',
        ),
        migrations.AddField(
            model_name='how_it_works',
            name='icon',
            field=models.CharField(choices=[('search', 'search'), ('apply', 'apply'), ('get', 'get')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
