# Generated by Django 5.0.1 on 2024-01-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_how_it_works_img_how_it_works_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='News',
        ),
    ]
