# Generated by Django 5.0.1 on 2024-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_blog_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_img', models.ImageField(upload_to='images/back_img/')),
            ],
        ),
    ]
